#Preprocessing
## first change Data cleaning: filename of e.g. raw171120 
## source('~/files/unipark/unipark/1Data cleaning unipark.R')
source('~/files/unipark/unipark/2calculate_PITandErrors2.R')
source('~/files/unipark/unipark/3PIT_Score function2.R')
source('~/files/unipark/unipark/4additional scales.R')
source('~/files/unipark/unipark/4Deviation.R')
source('~/files/unipark/unipark/5calculate AQ.R')
source('~/files/unipark/unipark/6calculate AQ subscores.R')
source('~/files/unipark/unipark/7calculate EQ.R')
source('~/files/unipark/unipark/7calculate EQ.R')
source('~/files/unipark/unipark/8calculate SQ.R')
source('~/files/unipark/unipark/9GUF und subscales.R')
source('~/files/unipark/unipark/10MSI und subscales.R')
source('~/files/unipark/unipark/11change class.R')
source('~/files/unipark/unipark/14Handedness.R')
source('~/files/unipark/unipark/12results.R')
source('~/files/unipark/unipark/13Filter.R')
source('~/files/AEFT/AEFT_Functions29.09.R')
source('~/files/AEFT/readloopAEFT.R')
source('~/files/AEFT/AEFT_loop29.09function.R')
source('~/files/AEFT/SDT_measures.R')
source('~/files/AGLT/AGLT_Functions27.09.R')
source('~/files/AGLT/readloopAGLT.R')
source('~/files/AGLT/AGLT_loop27.09function.R')
source('~/files/AGLT/SACS_measuresAGLT3.R')
source('~/files/Navon/Navon_Functions27.09.R')
source('~/files/Navon/readloopNavon.R')
source('~/files/Navon/Navon_loop27.09function.R')
source('~/files/Navon/SACS_measuresNavon3.R')
source('~/files/PAT/readloopPAT.R')
source('~/files/PAT/APdeviation_loop.R')
source('~/files/PAT/PAT_AR13case.R')
source('~/files/PAT/PAT_RI15SON966case.R')#hat zwei trials weniger
source('~/files/PAT/PAT_measures2.R')
source('~/files/PAT/APtime_loop.R')
source('~/files/Cognition/music_hours.R')
library(readr)
Cognition05.03 <- read_csv("~/files/Cognition/05.03.18_Testauswertung_AP_RP.csv")
## change filename Cognition in match results table 
## source('~/files/match result tables.R')
